CREATE TABLE user_details (uid SERIAL PRIMARY KEY, name VARCHAR(30), password VARCHAR(30), address VARCHAR(50), mobile VARCHAR(10), email varchar(40));

CREATE TABLE user_role_management(rid SERIAL, uid INT , ADMIN_Ius D INT, ROLE VARCHAR(10),FOREIGN KEY (UID) REFERENCES user_details (uid), FOREIGN KEY (admin_id) REFERENCES user_details (uid), primary key (rid, uid));

    DROP TABLE SENSOR_VALUE;
    DROP TABLE SENSOR_PARAMETERS;
    DROP TABLE DEVICE_MANAGEMENT;
    DROP TABLE DEVICE;

CREATE TABLE DEVICE (DEVICE_ID VARCHAR(20), LOGITUDE VARCHAR(20), LATITUDE VARCHAR(20), DESCRIPTION VARCHAR(50), PRIMARY KEY (device_id));

INSERT INTO DEVICE VALUES ('1014', '190273', '029380', 'Location');
INSERT 0 1


CREATE TABLE DEVICE_MANAGEMENT(UID INT, DEVICE_ID VARCHAR(20), ACCESS BOOLEAN, PRIMARY KEY(UID, DEVICE_ID), FOREIGN KEY (UID) REFERENCES user_details (uid), FOREIGN KEY (device_id) REFERENCES DEVICE (DEVICE_ID));


CREATE TABLE SENSOR_PARAMETERS(SLAVE_ID INT,DEVICE_ID INT, REG_ADD INT,KEYS VARCHAR(40), MINVALUE INT, MAXVALUE INT, SIUNIT VARCHAR(5), FOREIGN KEY (DEVICE_ID) REFERENCES DEVICE (DEVICE_ID), PRIMARY KEY (DEVICE_ID,REG_ADD,SLAVE_ID));

INSERT INTO SENSOR_PARAMETERS values('3','1014','0','R',0,1000,'Volts');
INSERT INTO SENSOR_PARAMETERS values('3','1014','2','Y',0,1000,'Volts');
INSERT INTO SENSOR_PARAMETERS values('3','1014','4','B',0,1000,'Volts');
INSERT INTO SENSOR_PARAMETERS values('3','1014','56','Frequency',0,1000,'Hz');
INSERT INTO SENSOR_PARAMETERS values('2','1014','2','pH',0,1000,'Value');
INSERT INTO SENSOR_PARAMETERS values('2','1014','3','Temprature',0,1000,'°C');
INSERT INTO SENSOR_PARAMETERS values('7','1014','0','Weight',0,1000,'KG');


CREATE TABLE SENSOR_VALUE (DEVICE_ID VARCHAR(20),SENSOR_ID VARCHAR(20),REG_ADD INT,VALUE FLOAT, U_TIME TIMESTAMP,PRIMARY KEY (DEVICE_ID, SENSOR_ID, REG_ADD, U_TIME),FOREIGN KEY (DEVICE_ID, REG_ADD, SENSOR_ID) REFERENCES SENSOR_PARAMETERS(DEVICE_ID, REG_ADD, SLAVE_ID));



ALTER TABLE user_details ALTER COLUMN mobile TYPE VARCHAR(10);

SELECT
  sv.device_id AS "Device ID",
  MAX(CASE WHEN sp.reg_add = '0' And sv.slave_id = '3' THEN sv.value END) AS "R",
  MAX(CASE WHEN sp.reg_add = '2' AND sv.slave_id = '3' THEN sv.value END) AS "Y",
  MAX(CASE WHEN sp.reg_add = '4' And sv.slave_id ='3' THEN sv.value END) AS "B",
  MAX(CASE WHEN sp.reg_add = '56' AND sv.slave_id ='3' THEN sv.value END) AS "Frequency",
  MAX(CASE WHEN sp.reg_add = '2' AND sv.slave_id = '2' THEN sv.value END) AS "Ph",
  MAX(CASE WHEN sp.reg_add = '3' And sv.slave_id = '2' THEN sv.value END) AS "Temperature",
   MAX(CASE WHEN sp.reg_add = '0' AND sv.slave_id='7' THEN sv.value END) AS "Weight",
  TO_CHAR(MAX(sv.u_time), 'YYYY-MM-DD HH24:MI') AS "Time"
FROM
  sensor_value sv
JOIN
  sensor_parameters sp ON sv.device_id = sp.device_id AND sv.slave_id = sp.slave_id AND sv.reg_add = sp.reg_add
WHERE
  sv.device_id = '1014'
GROUP BY
  sv.device_id, TO_CHAR(sv.u_time, 'YYYY-MM-DD HH24:MI')
ORDER BY
  "Time" DESC LIMIT 1;


